version: '3'
services:
  app:
    container_name: "activity-tracker-app"
    image: activity-tracker-app
    environment:
      - MONGO_HOST=mongodb
    ports:
      - 5000:8080
    links:
      - mongodb
    depends_on:
      - mongodb
  mongodb:
    image: "mongo:3.4"
    container_name: "mongodb"
    volumes:
      - ~/data/db:/data/db
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    container_name: "mongo-express"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb
    ports:
      - "8081:8081"